// Purpose: Defines for every ANSI code.
// Created on: 3/29/22 @ 11:27 AM

// Copyright (c) 2022, PortalPlayer
// Licensed under MIT <https://opensource.org/licenses/MIT>

#pragma once

#include "Internal/CppSupport.h"

SEC_CPP_SUPPORT_GUARD_START()
typedef enum {
    SEC_ANSI_CODE_BOLD,
    SEC_ANSI_CODE_UNDERLINE,
    SEC_ANSI_CODE_BLINKING,
    SEC_ANSI_CODE_INVERSE,
    SEC_ANSI_CODE_RESET,
    SEC_ANSI_CODE_FOREGROUND_BLACK,
    SEC_ANSI_CODE_FOREGROUND_RED,
    SEC_ANSI_CODE_FOREGROUND_GREEN,
    SEC_ANSI_CODE_FOREGROUND_YELLOW,
    SEC_ANSI_CODE_FOREGROUND_BLUE,
    SEC_ANSI_CODE_FOREGROUND_MAGENTA,
    SEC_ANSI_CODE_FOREGROUND_CYAN,
    SEC_ANSI_CODE_FOREGROUND_WHITE,
    SEC_ANSI_CODE_FOREGROUND_DEFAULT,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_BLACK,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_RED,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_GREEN,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_YELLOW,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_BLUE,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_MAGENTA,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_CYAN,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_WHITE,
    SEC_ANSI_CODE_BRIGHT_FOREGROUND_RESET,
    SEC_ANSI_CODE_BACKGROUND_BLACK,
    SEC_ANSI_CODE_BACKGROUND_RED,
    SEC_ANSI_CODE_BACKGROUND_GREEN,
    SEC_ANSI_CODE_BACKGROUND_YELLOW,
    SEC_ANSI_CODE_BACKGROUND_BLUE,
    SEC_ANSI_CODE_BACKGROUND_MAGENTA,
    SEC_ANSI_CODE_BACKGROUND_CYAN,
    SEC_ANSI_CODE_BACKGROUND_WHITE,
    SEC_ANSI_CODE_BACKGROUND_RESET,

    /**
     * Not a real code
     */
    SEC_ANSI_CODE_SIZE
} SEC_ANSI_Codes;

int SEC_ANSI_IsEnabled(void);
const char* SEC_ANSI_ConvertCodeToString(SEC_ANSI_Codes ansi);
SEC_CPP_SUPPORT_GUARD_END()
