// Purpose: Defines for all the built-in arguments.
// Created on: 9/11/22 @ 12:40 AM

#pragma once

#define SEC_BUILTINARGUMENTS_HELP "--help"
#define SEC_BUILTINARGUMENTS_CLIENT "--client"
#define SEC_BUILTINARGUMENTS_CLIENT_SHORT "-c"
#define SEC_BUILTINARGUMENTS_SERVER "--server"
#define SEC_BUILTINARGUMENTS_SERVER_SHORT "-s"
#define SEC_BUILTINARGUMENTS_NO_STRICT "--no-strict"
#define SEC_BUILTINARGUMENTS_NO_STRICT_SHORT "-ns"
#define SEC_BUILTINARGUMENTS_DONT_PARSE "--"
#define SEC_BUILTINARGUMENTS_WIDTH "--width"
#define SEC_BUILTINARGUMENTS_HEIGHT "--height"
#define SEC_BUILTINARGUMENTS_RENDERER "--renderer"
#define SEC_BUILTINARGUMENTS_SOFTWARE "--software"
#define SEC_BUILTINARGUMENTS_MONITOR "--monitor"
#define SEC_BUILTINARGUMENTS_DISABLE_ANSI_COLORING "--disable-ansi-coloring"
#define SEC_BUILTINARGUMENTS_DISABLE_ANSI_COLORING_SHORT "-dac"
#define SEC_BUILTINARGUMENTS_LOG_LEVEL "--log-level"
#define SEC_BUILTINARGUMENTS_LOG_LEVEL_SHORT "-ll"
#define SEC_BUILTINARGUMENTS_DONT_CHANGE_LOG_LEVELS "--dont-change-log-levels"
#define SEC_BUILTINARGUMENTS_DONT_CHANGE_LOG_LEVELS_SHORT "-dcll"
#define SEC_BUILTINARGUMENTS_DISABLE_UI_RENDERING "--disable-ui-rendering"
#define SEC_BUILTINARGUMENTS_DISABLE_UI_RENDERING_SHORT "-dur"
#define SEC_BUILTINARGUMENTS_EXIT "--exit"
#define SEC_BUILTINARGUMENTS_CONSOLE "--console"
